project:
  type: website
  output-dir: docs
  resources:
    - files

website:
  title: "My Website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
    right:
      - icon: github
        href: https://github.com/Austin-Li7/AustinLiWeb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
